NumPy’s main object is the homogeneous multidimensional array.

In NumPy dimensions are called axes. The number of axes is rank.

Ex: 1) [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3.

Ex :2)[[ 1., 0., 0.],[ 0., 1., 2.]] ,he array has rank 2 (it is 2-dimensional).

The first dimension (axis) has a length of 2, the second dimension has a length of 3.

In [1]:
import numpy as np


In [2]:
a = np.arange(6) 


In [3]:
print(a)


[0 1 2 3 4 5]


In [4]:
b = np.arange(12).reshape(4,3)  

In [5]:
print(b)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
c = np.arange(24).reshape(2,3,4)


In [8]:
print(c)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [14]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [16]:
np.full((3, 5), 3.14)


array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [17]:
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.linspace(0, 1, 5)


array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [21]:
np.random.random((3, 3))


array([[ 0.88549783,  0.01076862,  0.72242953],
       [ 0.93223165,  0.29280597,  0.82991211],
       [ 0.55515269,  0.20910461,  0.38538468]])

In [22]:
np.eye(3)


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [24]:
a = np.arange(15).reshape(3, 5)


In [25]:
print a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [26]:
a.shape

(3, 5)

In [27]:
a.ndim


2

In [28]:
a.dtype.name


'int64'

In [29]:
a.itemsize


8

In [30]:
a.size


15

In [31]:
b = np.array([6, 7, 8])


In [32]:
b


array([6, 7, 8])

In [33]:
type(b)


numpy.ndarray

In [34]:
a = np.array( [20,30,40,50] )


In [35]:
b = np.arange( 4 )


In [36]:
a

array([20, 30, 40, 50])

In [37]:
b

array([0, 1, 2, 3])

In [38]:
c = a+b

In [39]:
c

array([20, 31, 42, 53])

In [40]:
d= a-b


In [41]:
d

array([20, 29, 38, 47])

In [42]:
e = a*b


In [43]:
e

array([  0,  30,  80, 150])

In [44]:
f = a/b

/Users/aribahmehreen/.virtualenvs/keras_tf/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


In [45]:
f

array([ 0, 30, 20, 16])

In [48]:
A = np.array([[1,1], [0,1]])

In [49]:
B = np.array( [[2,0],[3,4]])


In [50]:
A*B


array([[2, 0],
       [0, 4]])

In [51]:
A.dot(B) 

array([[5, 4],
       [3, 4]])

In [52]:
np.dot(A, B)  

array([[5, 4],
       [3, 4]])

In [53]:
a = np.ones((2,3))

In [54]:
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [57]:
b = np.random.random((2,3))


In [58]:
b

array([[ 0.48579745,  0.5476104 ,  0.72907101],
       [ 0.70118585,  0.73743   ,  0.57982724]])

In [59]:
a *= 3


In [60]:
a

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [61]:
b += a


In [62]:
b

array([[ 3.48579745,  3.5476104 ,  3.72907101],
       [ 3.70118585,  3.73743   ,  3.57982724]])

In [63]:
a = np.random.random((2,3))

In [64]:
a

array([[ 0.97155283,  0.07121623,  0.23722243],
       [ 0.41424979,  0.04383785,  0.24763077]])

In [65]:
a.sum()


1.9857098855663278

In [66]:
a.min()


0.043837845873688441

In [67]:
a.max()


0.97155282570128887

In [68]:
b = np.arange(12).reshape(3,4)

In [69]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
# sum of each column
b.sum(axis=0) 


array([12, 15, 18, 21])

In [71]:
# min of each row

In [72]:
b.min(axis=1)      

array([0, 4, 8])

In [75]:
#One-dimensional array
x1 = np.random.randint(10, size=6) 

In [74]:
x1

array([8, 2, 4, 2, 4, 1])

In [77]:
# Two-dimensional array
x2 = np.random.randint(10, size=(3, 4))

In [79]:
x2

array([[3, 5, 1, 6],
       [4, 1, 1, 2],
       [5, 1, 9, 7]])

In [78]:
# Three-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))

In [80]:
x3

array([[[9, 0, 1, 4, 4],
        [6, 2, 8, 5, 4],
        [6, 7, 8, 0, 5],
        [6, 0, 9, 5, 3]],

       [[4, 2, 4, 2, 7],
        [7, 2, 2, 3, 8],
        [9, 7, 0, 8, 0],
        [3, 1, 3, 6, 8]],

       [[4, 4, 8, 3, 6],
        [3, 0, 3, 6, 0],
        [4, 2, 6, 5, 0],
        [2, 3, 6, 9, 5]]])

In [81]:
print("x3 ndim: ", x3.ndim)


('x3 ndim: ', 3)


In [82]:
print("x3 shape:", x3.shape)

('x3 shape:', (3, 4, 5))


In [83]:
print("x3 size: ", x3.size)


('x3 size: ', 60)


In [84]:
print("dtype:", x3.dtype)


('dtype:', dtype('int64'))


In [85]:
x1


array([8, 9, 9, 7, 2, 5])

In [86]:
x1[0]


8

In [87]:
x1[4]


2

In [88]:
x1[-1]

5

In [89]:
x1[-2]


2

In [90]:
x2

array([[3, 5, 1, 6],
       [4, 1, 1, 2],
       [5, 1, 9, 7]])

In [91]:
x2[0, 0]


3

In [92]:
x2[2, 0]


5

In [93]:
x2[2, -1]


7

In [94]:
x2[0, 0] = 12


In [95]:
x2


array([[12,  5,  1,  6],
       [ 4,  1,  1,  2],
       [ 5,  1,  9,  7]])