In [1]:
from sklearn.cluster import KMeans

In [3]:
import numpy as np

In [4]:
X = np.array([[1, 2], [1, 4], [1, 0],[4, 2], [4, 4], [4, 0]])

In [11]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

In [12]:
kmeans.labels_

array([0, 0, 0, 1, 1, 1], dtype=int32)

In [13]:
kmeans.predict([[0, 0], [4, 4]])

array([0, 1], dtype=int32)

In [14]:
kmeans.cluster_centers_

array([[ 1.,  2.],
       [ 4.,  2.]])